version: "3.3"
services:
  database:
    build: database
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_USER: ${DATABASE_USER_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_USER_PASSWORD}
  server:
    build: server
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER_NAME: ${DATABASE_USER_NAME}
      DATABASE_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
    ports:
      - 8080:8000
      - 8090:8090
    tty: true
    volumes:
      - ./server/app:/app
