version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers

    environment:
      APP_KEY: base64:7f+EBTolSBVkgoBRjujde06KHk6H2eo4Ev91Fkb4t3E=

    working_directory: ~/project/server/app/CutModelMatching

    steps:
      - checkout:
          path: ~/project

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run: composer test
